Create Redis connector plugin
podkolzzzin/QueryPressure pull request #6
Opened 2022-11-11 11:00 UTC by TheHACKATHON

2022-11-11 11:01 UTC, TheHACKATHON commented on src/QueryPressure.Postgres.App/PostgesConnectionProviderCreator.cs
> +[assembly: QueryPressurePlugin]
Сделал постгрес плагином

2022-11-11 11:02 UTC, TheHACKATHON commented on src/QueryPressure.Redis.Core/RedisConnectionProvider.cs
> +  public sealed class RedisConnectionProvider : IConnectionProvider
базовьіе классьі не получилось использовать, коннектор редиса не имплементит IDbConnection

2022-11-15 13:30 UTC, podkolzzzin requested changes

2022-11-15 15:50 UTC, TheHACKATHON commented on src/QueryPressure.Redis.Core/RedisConnectionProvider.cs
> +  public sealed class RedisConnectionProvider : IConnectionProvider
done

2022-11-16 08:31 UTC, podkolzzzin requested changes

2022-11-16 08:50 UTC, podkolzzzin approved these changes

2022-11-16 08:50 UTC, merged