Create SqlServer provider
podkolzzzin/QueryPressure pull request #9
Opened 2022-11-12 20:47 UTC by TheHACKATHON

2022-11-15 13:34 UTC, podkolzzzin requested changes

2022-11-15 13:34 UTC, podkolzzzin commented on src/QueryPressure.SqlServer.Core/QueryPressure.SqlServer.Core.csproj
> +      <PackageReference Include="Dapper" Version="2.0.123" />
Is it really needed?

2022-11-15 13:46 UTC, TheHACKATHON commented on src/QueryPressure.SqlServer.Core/QueryPressure.SqlServer.Core.csproj
> +      <PackageReference Include="Dapper" Version="2.0.123" />
Nope. Removed

2022-11-16 08:32 UTC, podkolzzzin approved these changes

2022-11-16 08:33 UTC, merged